"""add cash closing totals

Revision ID: 2aaf31952c63
Revises: 468ddca2d7f4
Create Date: 2026-10-07 09:46:17.859260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aaf31952c63'
down_revision: Union[str, Sequence[str], None] = '468ddca2d7f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_sessions', sa.Column('theoretical_cash', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('cash_sessions', sa.Column('cash_difference', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cash_sessions', 'cash_difference')
    op.drop_column('cash_sessions', 'theoretical_cash')
    # ### end Alembic commands ###
