"""create cash movements

Revision ID: 468ddca2d7f4
Revises: 2c5e859ff73c
Create Date: 2026-10-07 09:35:12.699948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468ddca2d7f4'
down_revision: Union[str, Sequence[str], None] = '2c5e859ff73c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("movement_type IN ('SALE', 'INCOME', 'EXPENSE', 'WITHDRAWAL', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT')", name='ck_cash_movement_type'),
    sa.CheckConstraint("payment_method IN ('CASH', 'TRANSFER', 'DEBIT', 'CREDIT', 'OTHER')", name='ck_cash_payment_method'),
    sa.CheckConstraint('amount > 0', name='ck_cash_movement_amount_positive'),
    sa.ForeignKeyConstraint(['cash_session_id'], ['cash_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cash_movements_created_at', 'cash_movements', ['created_at'], unique=False)
    op.create_index('ix_cash_movements_session_id', 'cash_movements', ['cash_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cash_movements_session_id', table_name='cash_movements')
    op.drop_index('ix_cash_movements_created_at', table_name='cash_movements')
    op.drop_table('cash_movements')
    # ### end Alembic commands ###
