"""add stock units and product conversions

Revision ID: 595c5f1f7597
Revises: 7147194fdfd7
Create Date: 2026-10-06 15:26:21.376047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '595c5f1f7597'
down_revision: Union[str, Sequence[str], None] = '7147194fdfd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_product_id', sa.Integer(), nullable=False),
    sa.Column('target_product_id', sa.Integer(), nullable=False),
    sa.Column('source_quantity', sa.Integer(), nullable=False),
    sa.Column('target_quantity', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['source_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['target_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_product_id', 'target_product_id', name='uq_product_conversion')
    )
    op.add_column('products', sa.Column('stock_unit', sa.String(length=20), server_default='UNIT', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock_unit')
    op.drop_table('product_conversions')
    # ### end Alembic commands ###
