"""add sale cancellation audit

Revision ID: 8fab9dd8671c
Revises: 319cf347a26f
Create Date: 2026-10-07 10:36:45.224871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fab9dd8671c'
down_revision: Union[str, Sequence[str], None] = '319cf347a26f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('canceled_by_user_id', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sales', sa.Column('cancel_reason', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'sales', 'users', ['canceled_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'cancel_reason')
    op.drop_column('sales', 'canceled_at')
    op.drop_column('sales', 'canceled_by_user_id')
    # ### end Alembic commands ###
