"""add product price unit quantity

Revision ID: e4646f37a6cd
Revises: 8fab9dd8671c
Create Date: 2026-10-07 11:40:27.242116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4646f37a6cd'
down_revision: Union[str, Sequence[str], None] = '8fab9dd8671c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price_unit_quantity', sa.Integer(), server_default='1', nullable=False))
    op.add_column('sale_items', sa.Column('price_unit_quantity', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_items', 'price_unit_quantity')
    op.drop_column('products', 'price_unit_quantity')
    # ### end Alembic commands ###
